### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by ghost** [minwork/react-interval-hook#14]
I'm getting that error with description: SyntaxError: Cannot use import statement outside a module.

Any idea how I can make it work with Jest?

**Comment by minwork** [comment]
Hey, I am not sure what may be the exact cause but you can try to import some specific version from `dist` folder (see [code on npm](https://www.npmjs.com/package/react-interval-hook?activeTab=code)) like `dist/index.umd.js`. 

If that not work, I plan to migrate this hook to [new repo](https://github.com/minwork/react) and unify configuration with my other hooks which should probably solve this problem.

**Comment by minwork** [comment]
@andrea-magazzini should be solved in `react-interval-hook@1.1.4`, in case it is not please create new issue in [this repo](https://github.com/minwork/react)
